version: "3.9"

services:
  fast_api:
    image: datascientest/fastapi:1.0.0
    container_name: test_fast_api_container
    ports:
      - "8000:8000"
    networks:
      - myNetwork_from_fast_api

  authentication_test:
    image: docker_authentication:latest
    container_name: test_authentication
    depends_on:
      - fast_api
    #référencer chaque Dockerfile en spécifiant le chemin du contexte de build
    build:
      context: ./authentication_test
    networks:
      - myNetwork_from_fast_api
    environment:
      - LOG=1
    volumes:
      - logs:/app/logs

  authorization_test:
    image: docker_authorization:latest
    container_name: test_authorization
    depends_on:
      - fast_api
    build:
      context: ./authorization_test
    networks:
      - myNetwork_from_fast_api
    environment:
      - LOG=1
    volumes:
      - logs:/app/logs

  content_test:
    image: docker_content:latest
    container_name: test_content
    depends_on:
      - fast_api
    #référencer chaque Dockerfile en spécifiant le chemin du contexte de build
    build:
      context: ./content_test
    networks:
      - myNetwork_from_fast_api
    environment:
      - LOG=1
    volumes:
      - logs:/app/logs

volumes:
  logs:


networks:
  myNetwork_from_fast_api:
    driver: bridge
